name = "c++"

[fs]
base = "/var/lib/docker/overlay2/v58a2bw0rddwkryn4v2cjv4xz/diff:/var/lib/docker/overlay2/7os82h4vbyz8pypvwwfj8q7xh/diff:/var/lib/docker/overlay2/rhhkdtm0iovm9vqslladnic09/diff:/var/lib/docker/overlay2/a467928a9d31383830f4483cab85fed9b58e06799ae1d3f203b0d9af3d9baaac/diff"
workdir = "/code"

[cmd]
compile = "/usr/bin/g++ -fno-asm -Wall -lm --static -O2 -std=c++14 -DONLINE_JUDGE -o /code/Main /code/Main.cc"
run  = "/code/Main"
ver = "/usr/bin/g++ --version"

