name = "Go"

[fs]
base = "/var/lib/docker/overlay2/f30d2419a81af352b788625616f2350232d52b6a6d715f7b296a7c2398446c44/diff:/var/lib/docker/overlay2/754d5e0de59d752a8cca8b0db5fd0efa5b844f852e94445ae23d53c941c3d3b7/diff:/var/lib/docker/overlay2/bef57cfc8b198185eaf45527a12c1028ba4a494ae2633c57aa323c0d06fe4d4b/diff:/var/lib/docker/overlay2/0f3379e001b2a4eb089fe614b806ae3c04ef477bacd1625a483b4c7524cbef16/diff:/var/lib/docker/overlay2/7fd11b20da7d2c5bc1b35afd9f5b26d63ba492dd6a78d1038253bdbad1b88476/diff:/var/lib/docker/overlay2/ac8520bb63ddf456918968b7a920b6ecdbd84afde8e8628d7c1f3aae06d92426/diff:/var/lib/docker/overlay2/8e1226e176214f841034674d508775b71a61d493243109beeccc32cf5c714b33/diff:/var/lib/docker/overlay2/0e41dca9a1b50ff520a92c999216df6e7d6c5910fbd10f97e5af34c917ca6c9d/diff"
workdir = "/code"

[cmd]
compile = "/usr/local/go/bin/go build -o Main Main.go"
run  = "/code/Main"
ver = "/usr/local/go/bin/go version"
env = ["ONLINE_JUDGE=1", "GOROOT=/usr/local/go", "HOME=/tmp", "GOCACHE=/go-cache", "GOTELEMETRY=off"]
