name = "pascal"

[fs]
base = "/var/lib/docker/overlay2/45f47c54d629c5cc5949f705e42749081b8f2c0423f0002d635901b018572da3/diff:/var/lib/docker/overlay2/a467928a9d31383830f4483cab85fed9b58e06799ae1d3f203b0d9af3d9baaac/diff"
workdir = "/code"

[cmd]
compile = "/usr/bin/fpc Main.pas -oMain -O1 -Co -Cr -Ct -Ci"
run  = "/code/Main"
ver = "/usr/bin/fpc -v"

