name = "Go"

[fs]
base = "/var/lib/docker/overlay2/0f3379e001b2a4eb089fe614b806ae3c04ef477bacd1625a483b4c7524cbef16/diff:/var/lib/docker/overlay2/7fd11b20da7d2c5bc1b35afd9f5b26d63ba492dd6a78d1038253bdbad1b88476/diff:/var/lib/docker/overlay2/ac8520bb63ddf456918968b7a920b6ecdbd84afde8e8628d7c1f3aae06d92426/diff:/var/lib/docker/overlay2/8e1226e176214f841034674d508775b71a61d493243109beeccc32cf5c714b33/diff:/var/lib/docker/overlay2/0e41dca9a1b50ff520a92c999216df6e7d6c5910fbd10f97e5af34c917ca6c9d/diff"
workdir = "/code"

[cmd]
compile = "/usr/local/cargo/bin/rustc -o Main Main.rs"
run  = "/code/Main"
ver = "/usr/local/cargo/bin/rustc --version"
