name = "java"

[fs]
base = "/var/lib/docker/overlay2/c17ba7849c16468357609c9110758f4e3e8f2b5a9f9c228d413ca0c96c6e494d/diff:/var/lib/docker/overlay2/595e3ccff82bb0f3cf70023dc1801cd39976fec35d1b0e57bd8e3735cbb1d9cc/diff:/var/lib/docker/overlay2/4dd6633dd81456ff56dc6dbc642d123752e94dc8e70837167e24fad20d03fb00/diff:/var/lib/docker/overlay2/bd07fb6810e2055ce9704d469dccd8d6e7c729495ec0bc38bd7ec0f758efb9ba/diff:/var/lib/docker/overlay2/a467928a9d31383830f4483cab85fed9b58e06799ae1d3f203b0d9af3d9baaac/diff"
workdir = "/code"

[cmd]
compile = "/usr/bin/javac Main.java"
run  = "/usr/bin/java Main"
ver = "/usr/bin/javac --version"
env = ["ONLINE_JUDGE=1"]
