name = "Shell"

[fs]
base = "/var/lib/docker/overlay2/680498683ccbc9f5e220400373e8702900cfab3f2ca29ea8f909920465d5090c/diff:/var/lib/docker/overlay2/0e41dca9a1b50ff520a92c999216df6e7d6c5910fbd10f97e5af34c917ca6c9d/diff"
workdir = "/code"

[cmd]
compile = "/bin/busybox dos2unix Main.sh"
run  = "/bin/bash /code/Main.sh"
ver = "/bin/bash --version"
